services:
  pigallery-db:
    container_name: pigallery-db
    image: mariadb
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?Set MYSQL_ROOT_PASSWORD in .env}
      MYSQL_USER: ${MYSQL_USER:-pigallery2}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:?Set MYSQL_PASSWORD in .env}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-pigallery2}

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/error.log:/etc/nginx/error_log.log
      - ./nginx/cache/:/etc/nginx/cache
      - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - 80:80
      - 443:443
    restart: always

  pigallery2:
    image: railline/pigallery2plus:latest
    command:
      - --Database-type=mysql
      - --Database-mysql-host=pigallery-db
      - --Database-mysql-username=${MYSQL_USER:-pigallery2}
      - --Database-mysql-password=${MYSQL_PASSWORD:?Set MYSQL_PASSWORD in .env}
      - --Database-mysql-database=${MYSQL_DATABASE:-pigallery2}
    container_name: pigallery2plus
    deploy:
      resources:
        limits:
          memory: 3G # <1GB RAM might also work. It will trigger GC more often. GC is slow. See https://github.com/bpatrik/pigallery2/issues/1080
    environment:
      - NODE_ENV=production # set to 'debug' for full debug logging
      - DATABASE_TYPE=mysql
      - MYSQL_HOST=pigallery-db
      - MYSQL_PORT=3306
      # - NODE_OPTIONS=--enable-source-maps # enable source map support on the backend  for development
    volumes:
      - "./pigallery2/config:/app/data/config" # CHANGE ME
      - "db-data:/app/data/db"
      - "./pigallery2/images:/app/data/images:ro" # CHANGE ME, ':ro' means read-only
      - "./pigallery2/tmp:/app/data/tmp" # CHANGE ME
    expose:
      - "80"
    depends_on:
      - pigallery-db
    restart: always

volumes:
  db-data:
