# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Lint Dockerfiles

on:
  push:
    branches:
      - '**'

jobs:
  dockerfile_linting:
    name: Dockerfile linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      - name: Lint Alpine Dockerfile
        uses: hadolint/hadolint-action@54c9adbab1582c2ef04b2016b760714a4bfde3cf # v3.1.0
        with:
          dockerfile: ./docker/alpine/Dockerfile.build
          config: ./docker/.config/hadolint.yml
      - name: Lint Debian Trixie Dockerfile
        uses: hadolint/hadolint-action@54c9adbab1582c2ef04b2016b760714a4bfde3cf # v3.1.0
        with:
          dockerfile: ./docker/debian-trixie/Dockerfile.build
          config: ./docker/.config/hadolint.yml
      - name: Lint Debian Trixie Self-contained Dockerfile
        uses: hadolint/hadolint-action@54c9adbab1582c2ef04b2016b760714a4bfde3cf # v3.1.0
        with:
          dockerfile: ./docker/debian-trixie/selfcontained/Dockerfile
          config: ./docker/.config/hadolint.yml
